### ISSUE TITLE
Not working for 10.3.1.0 stable.

### ISSUE THREAD

**Issue by Tennyleaz** [GreatApo/MiNote3-Camera2API-fix#1]
The mod was working on miui stable / xiaomi.eu stabe 10.2, but not working on 10.3.1.0.
Stock miui camera results a black screen, and google camera will force close.

**Comment by GreatApo** [comment]
I had this problem but I thought it was caused by the permission. Try to reboot the phone a couple of times. I will be testing it through each new version.

**Comment by GreatApo** [comment]
I uploaded a new release. There was a problem in the build.prop edit.

You can also try with commands from PC, this will work:
[Camera-Fix.zip](https://github.com/GreatApo/MiNote3-Camera2API-fix/files/3098471/Camera-Fix.zip)

**Comment by GreatApo** [comment]
Everything work now. The only problem is that the system doesn't mount automatically (script command doesn't work). Hence, before flash, the system has to manually be mounted.
